FROM scratch
MAINTAINER ape factory GmbH

# Add files
ADD elasticache-broker /elasticache-broker
ADD config.json /config.json

# Command to run
ENTRYPOINT ["/elasticache-broker"]
CMD ["--config=/config.json"]

# Expose listen ports
EXPOSE 3000
